//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tuga.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdditionalPhotos
    {
        public int ID { get; set; }
        public int IDDish { get; set; }
        public string Photo { get; set; }
    
        public virtual Dish Dish { get; set; }
    }
}
