//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tuga.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddIngridient
    {
        public int ID { get; set; }
        public int IDIngridient { get; set; }
        public int IDOrderDish { get; set; }
        public Nullable<int> QTY { get; set; }
    
        public virtual Ingridient Ingridient { get; set; }
        public virtual OrderDish OrderDish { get; set; }
    }
}
