//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tuga.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComplimentaryDish
    {
        public int ID { get; set; }
        public int IDDishParent { get; set; }
        public int IDDishChild { get; set; }
    
        public virtual Dish Dish { get; set; }
        public virtual Dish Dish1 { get; set; }
    }
}
